name: stroll_app_01
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_launcher_icons: ^0.14.2
  flutter_svg: ^2.0.16
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3

flutter:

  uses-material-design: true

  assets:
    - assets/media/icons/png/
    - assets/media/icons/svg/
    - assets/media/images/
    - assets/media/video/


  fonts:
    - family: nunito_sans
      fonts:
        - asset: assets/font/nunito_sans.ttf